name: Daily Script Run

on:
  schedule:
    - cron: '0 11 * * 1-6 # Runs every day at midnight UTC

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x' # Choose the Python version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt # If you have any dependencies, replace requirements.txt with your requirements file if applicable

    - name: Run script
      run: python your_script.py
