name: Daily Script Run

on:
  schedule:
    - cron: '*/5 * * * *' # Runs every 5 minutes

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x' # Choose the Python version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        

    - name: Run script
      run: python Order-Cleaning-script/Order_data_cleaning.py
      env:
        DROPBOX_TOKEN: ${{ secrets.DROPBOX_TOKEN }}

    - name: Create completion marker
      run: echo "Workflow ran successfully" > workflow_completed.txt
